### ISSUE TITLE
Command operation bug

### ISSUE THREAD

**Issue by capticka** [RoanH/KeysPerSecond#100]
Hello, again.
I am telling you that there is an error in KeyPerSecond.
There is a command here, but it doesn't work well.
I reset the total, but the stats are reset, and I reset the stats again, but the total is reset.
Also, even if you press Ctrl + R for both total initialization and stat initialization, only one of the total or stats will be reset, and no matter how many times you press it again, it will not be reset.
That was a bit long. Please fix it.
V8.9

**Comment by RoanH** [comment]
Hello, I feel like there are multiple issues in this report:
1. `There is a command here, but it doesn't work well.`
The reset totals command <kbd>Ctrl</kbd>+<kbd>I</kbd> is perhaps named a bit misleading since it predates the total panel, this command only resets the total number of hits for each key panel (so not the total panel). I may rename it for the next release.
2. `I reset the total, but the stats are reset`
Stats refers to the aggregate panels, so MAX/AVG/KPS/TOT/LST, I can't reproduce these being reset by the reset totals command.
3. `and I reset the stats again, but the total is reset.`
The TOT panel is one of the stat panels together with MAX/AVG/KPS/LST, so this is intentional.
4. `Also, even if you press Ctrl + R for both total initialization and stat initialization, only one of the total or stats will be reset, and no matter how many times you press it again, it will not be reset.`
I can't reproduce this, all of the key panels and AVG/MAX/KPS/LST/TOT get reset to 0 if I run <kbd>Ctrl</kbd>+<kbd>R</kbd>.

Please let me know if I misunderstood something or if anything is unclear.

**Comment by capticka** [comment]
Why do I reset only the panels such as KPS, MAX, AVG, TOT, etc. even if I set the Reset stats and Reset totals commands with Ctrl + R?

**Comment by RoanH** [comment]
<kbd>Ctrl</kbd>+<kbd>R</kbd> is intended to reload the entire configuration, it resetting the counts is just a side effect. If you have automatic stats saving on exit and/or stats loading on launch enabled, then it won't even reset the stats at all since they'll be restored when you reload the config.

**Comment by capticka** [comment]
By any chance, can't this program execute two commands with the same command?

**Comment by RoanH** [comment]
Ah, that's an interesting use case. Setting the same key combination for different commands will indeed cause one of them to not execute, specifically, the precedence order is `reset stats > exit > reset totals > hide > pause > reload`. I suppose that since the key combinations are configurable now it would be better allow them to be bound more than once, I'll pick that up for the next release.

**Comment by capticka** [comment]
Oh, I think that was the problem. Thank you.

**Comment by RoanH** [comment]
Fixed this now for the next release (v8.10).
