### ISSUE TITLE
Add mouse button can't display normal key name.

### ISSUE THREAD

**Issue by MikiraSora** [RoanH/KeysPerSecond#11]
![image](https://user-images.githubusercontent.com/7549173/29279107-5d868736-8149-11e7-9c64-9b1c2a52f6fe.png)
![image](https://user-images.githubusercontent.com/7549173/29279131-72d88990-8149-11e7-9b4f-fd47749d31a9.png)

**Comment by RoanH** [comment]
Thank you for reporting this :)
This appears to be an issue that I accidentically caused later on.
I'm going to try and fix this as soon as possible.
In the meantime you can try using version 6.1 since it isn't affected by the bug (if some of the newer features aren't relevant to you).
I'll keep you updated.

**Comment by RoanH** [comment]
All fixed. I'll probably release version 6.6 later today.
