### ISSUE TITLE
Auto load configuration

### ISSUE THREAD

**Issue by Tsuk1ko** [RoanH/KeysPerSecond#20]
Hi, I really like this program and I have used it for a long time, very nice!

Is it possible to auto load configure? This may require storing additional configurations to AppData or somewhere.

If you do not like that, is it possible to attach the configuration file location in the form of command line parameters to boot directly to the main interface?

Thank you.

**Comment by RoanH** [comment]
Hi,

The main reason there is currently no support for that is indeed because I dislike storing data on the users system (especially AppData). However given that this feature is actually requested a lot I do have some plans to implement it via the GUI. Most likely I'll end up storing a small configuration file in the same folder as the exe/jar in that case (and probably make it optional).

There is already support to pass a configuration file via the command line though. If that stopped working please let me know!

And thank you for using KeysPerSecond ^_^

**Comment by Tsuk1ko** [comment]
Really! Sorry I missed the README. 😂

But it seems that it only work when accept an absolute path.

```bash
# not work
javaw -jar KeysPerSecond.jar xxx.kpsconf3
# work
javaw -jar KeysPerSecond.jar D:\\xxx.kpsconf3
```

**Comment by RoanH** [comment]
No worries 😄 

I might switch things up so that both forms are accepted, but for now only absolute paths work yeah.

**Comment by RoanH** [comment]
Starting from v8.8 it'll also be possible to configure a default configuration that the program launches with.
