### ISSUE TITLE
Feature Request: Custom key button names.

### ISSUE THREAD

**Issue by Lach993** [RoanH/KeysPerSecond#21]
Hey im a 4k OSU!Mania player and i use the keys 1 2 / * to play (/ * on numpad) but it shows up on the app as 1 2 / [print screen] (which is unreadable). i was wondering if you could add in a setting to customize the names for the keys so i could change them to 1234, that would also make it relate to the columns while playing
![image](https://user-images.githubusercontent.com/30387716/72675206-c8c6f980-3abb-11ea-969c-a6cdc87349dd.png) that is what it looks like for me.

**Comment by RoanH** [comment]
Hey,
This should already be possible (since [v8.2](https://github.com/RoanH/KeysPerSecond/releases/tag/v8.2)).

All you have to do is double click the name of a key on the edit/add keys page.
![afbeelding](https://user-images.githubusercontent.com/8530896/72682433-48a98f80-3acd-11ea-8984-aadb373bdbc5.png)

I agree that this could be more obvious (I added the note on that dialog to help with that). I do have plans to improve the clarity of some settings, but I haven't had the time...

**Comment by RoanH** [comment]
Closing this, please reopen if my previous comment did not address your issue 👀
