### ISSUE TITLE
Set the hotkey of resetting statistics to `Ctrl + I` even if the config file sets otherwise

### ISSUE THREAD

**Issue by UlyssesZh** [RoanH/KeysPerSecond#47]
If the config files defines the hotkey of resetting statistics, it is useless. KeysPerSecond always goes into the default hotkey `Ctrl + I`.

**Comment by RoanH** [comment]
Thanks for the report, this is a known issue #40. I've also actually already fixed it a while back, but I've been too busy to properly finish up the release... If you need an immediate workaround for this, I described one in the linked issue, but otherwise I'm really hoping to get the next release out during my christmas break.
