### ISSUE TITLE
Can't save config

### ISSUE THREAD

**Issue by HalluXcinogen** [RoanH/KeysPerSecond#61]
Hi!

Great work with this! It seems that when I try to save the config to a local find, it only opens the "Open File" window. It may be that I do something wrong, but both the Load config and Save config opens up the same window. I'm on a MacBook Pro M1.

Thanks in advance for your help!

**Comment by RoanH** [comment]
Hey, thanks for the report! Surprised it took this long for this to get reported. I checked and you're not doing anything wrong, I'm just mistakenly showing a file open dialog... I'll try to get this fixed as soon as possible, but I can't really give an exact time frame. If you have access to a Windows machine then you could make the configuration file on there and then copy over the saved configuration file, since I'm showing the correct dialog on Windows.

**Comment by HalluXcinogen** [comment]
No worries! It’s the same problem with save stats as well, just so you know it. I’ll try the solution going via Windows.

**Comment by RoanH** [comment]
Alright, config saving and stats saving share the same dialog yeah, so I'll fix that at the same time. Glad to hear that making the configuration on Windows is a possibility for you.

**Comment by RoanH** [comment]
Will be fixed in the next release (v8.7).
