### ISSUE TITLE
I want to know how to skip the configuration steps.

### ISSUE THREAD

**Issue by pjiyun1005** [RoanH/KeysPerSecond#65]
I already read your instructions to skip configuration steps but I couldn't understand it.
Can you explain me more specifically?

**Comment by RoanH** [comment]
Hi, there are essentially three ways to do this at the moment. In the future I intend to add a third even easier method where you can just have a configuration with a specific name in the same folder as the executable, but that's currently not a thing yet. As for the three options that work at the moment:

1. Instead of launching the executable try to execute the configuration file instead. That should prompt Windows to ask you for an application to open the file with. Then you need to scroll all the way to the bottom where you can manually locate a program and then you just give it the location of the KeysPerSecond executable. As long as you do not move the KeysPerSecond executable you should be able to launch the configuration by just double clicking your configuration file to launch the program.

2. You can write a small batch script that will launch the program with a specific configuration file. The content of the script is simply `"C:\path\to\KeysPerSecond.exe" "C:\path\to\config.kps"` (keep the quotes) and you save that as `somename.bat` (make sure it doesn't save as `.bat.txt`). Then you can just double click this file to launch the program with that config.

3. You can drag & drop your configuration file onto the KeysPerSecond executable and that will launch it with the given configuration file without showing any configuration steps.

**Comment by RoanH** [comment]
Added a slightly more extensive wiki page: https://github.com/RoanH/KeysPerSecond/wiki

**Comment by pjiyun1005** [comment]
Thank you for answering! It helped a lot!

**Comment by RoanH** [comment]
Great!
