### ISSUE TITLE
Cannot save configs

### ISSUE THREAD

**Issue by Tritical1** [RoanH/KeysPerSecond#67]
I press the "save config" button and it brings me to a menu for loading configs so what do I do? Mac Catalina is the OS I'm using.

**Comment by RoanH** [comment]
Hi, this is something I accidentally broke by accident at some point. I've fixed this last week (see #61) and the fix will be included in version 8.7. If possible you can make your configuration file on Windows and then transfer the file and load the saved configuration on Mac (since Windows is unaffected). If that's not an option please let me know so I can try to get the next release out faster (though I cannot promise anything).

**Comment by Tritical1** [comment]
lol i dont know where any flash drives are and im lazy to find them. also
take your time with 8.7, programming is a fine art i know nothing about,
besides the fact that it takes time. dont worry about some stranger thats
willing to wait.

**Comment by RoanH** [comment]
Version 8.7 will be out later today, thanks for waiting :)

**Comment by Tritical1** [comment]
thx man.
