### ISSUE TITLE
One small problem

### ISSUE THREAD

**Issue by T4M1L0S** [RoanH/KeysPerSecond#73]
Alright so I run KPS on my chromebook using linux, which does work and everything is good.

But the problem I have is that I can't move the display (when I click "OK" it appears right at the middle of my screen and **I can't move it** for example at the bottom-left of my screen).

I tried to hold-clicking it and it does nothing. So is there an option in the option panel (which appears with right-click) ?

If not, then it would be good to add a "move display" option (which can lead to 4 different options: bottom-left, bottom-right, top-left, top-right) or something else.

Anyways, hope you add an option like this for the next update or tell me if there is another possible way to move the display.

**Comment by RoanH** [comment]
Huh, interesting, hold-clicking and dragging is the intended method to move the window. Though there is already an alternative method that is more intended for pixel perfect positioning of the window. You can move the window with the arrow keys at 3 different speeds 1, 2 & 3 pixels at a time (2= when Ctrl is down, 3= when Shift is down). Though since the normal way of moving the window doesn't work I have no idea if this also doesn't work. Not entirely sure what could be causing the original issue though...

**Comment by T4M1L0S** [comment]
I tested with arrow keys and it doesn't work as well. (The same with the Ctrl key and Shift key)

I think it's because I use KPS with a **_chromebook_** and it seems to not work (KPS does work perfectly for me but it's just the window that doesn't want to move). I dunno if you have gotten replies from people that use a chromebook or if I'm the first one here.

So, maybe you could do the idea I suggested to you:

"it would be good to add a "move display" option in the panel menu (which can lead to 5 different options: bottom-left, bottom-right, bottom-middle, top-left, top-right,) or something else."

**Comment by RoanH** [comment]
I got the chromebook part, though there's no clear reason why that would interfere with moving the window. Adding another UI interaction to change the position would most likely not solve anything, since the internal system call to move the window would still be exactly the same. Are there any errors visible when running the application from the command line? (`java -jar  KeysPerSecond-v8.7.jar`)

One thing that might potentially work is setting the location of the window before the main window is shown. You can do that by setting the window position in the configuration file (which you can just edit with a plain text editor). You can either save a config with the on screen position and then edit that or manually add the `position: [x=0,y=0]` key (which denotes the pixel coordinates of the top left corner).

**Comment by T4M1L0S** [comment]
I do run with the line "java -jar  KeysPerSecond-v8.7.jar" and there aren't any visible errors.

I haven't tested your suggestion yet but if it works (or not) I will notice you.

**Comment by T4M1L0S** [comment]
Alright, it's finally working! Thanks for the suggestion, now I can use KPS properly. ^^

**Comment by RoanH** [comment]
Cool, glad to know that worked! I suppose that means that something on ChromeOS disallows updates to the position of a window after it is already displayed, though I doubt that there would be much I could do to fix that...

Either way, thank you for using KeysPerSecond ^_^
