### ISSUE TITLE
Data ruined.

### ISSUE THREAD

**Issue by PolandballMaster** [RoanH/KeysPerSecond#80]
I installed the mod and ran it for ADOFAI (A Dance of Fire and Ice) as I wanted to test it out. ADOFAI then crashed, which happens rarely, only due to lag. After rebooting it though, most of my data was gone. I still had the main 12 worlds and the custom levels, but everything else was gone. The Neo Cosmos data, the extra worlds. Gone. Did this have something to do with it?

PS: ADOFAI is a Steam game, so I made it an application. I also accidentally put the layout in both Steam and ADOFAI. I have a M1 Mac Venturea 13.2.1)

**Comment by RoanH** [comment]
This program runs as a completely separate process on your system, so it would be extremely unlikely for KeysPerSecond to have caused this. While this application looks like an overlay, note that it is technically not since it does not inject itself into games like e.g. the Discord or Steam overlay do (see feature request #28).

**Comment by PolandballMaster** [comment]
Alright, I understand, I think maybe turning ADOFAI (a steam game) into an application caused the data to be corrupted, and I think this issue could be closed.

**Comment by RoanH** [comment]
Sounds like a more probable cause yeah, either way, good luck with your investigation.

**Comment by PolandballMaster** [comment]
I realized what I did wrong, it was I clicked the application when trying to choose what layout I saved instead of the layout, which caused my game to crash.
