### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by Nyayurn** [RoanH/KeysPerSecond#86]
Error with Dragonwell 17
![Screen](https://github.com/RoanH/KeysPerSecond/assets/132195516/dbe59e78-86f2-4504-af33-076209afb760)
Error with Dragonwell 8
![Screen](https://github.com/RoanH/KeysPerSecond/assets/132195516/e5fa84a4-bf3c-40fd-963f-b923909cb10e)
System info
![Screen](https://github.com/RoanH/KeysPerSecond/assets/132195516/455a3c3f-633f-4dea-9a51-7000aec25353)

**Comment by RoanH** [comment]
Interesting error, but it appears like there is simply not enough free space in `/tmp`, which then causes the native library to fail to load. Whether there's actually not enough space I don't know. As far as I can tell you should be meeting all of the [system requirements](https://github.com/kwhat/jnativehook#software-and-hardware-requirements) just fine otherwise.

**Comment by Nyayurn** [comment]
I also encountered this problem toolbox running jetbrains before. At that time, I used temporary environment variables to change the tmp directory. Perhaps this problem can be solved in this way as well.

**Comment by RoanH** [comment]
If you wanted to you could pass a custom temp directory by changing the JVM `java.io.tmpdir` system property. Though it'd be user dependent what a sensible value would be to pass, so not really something I'd be able to really automate.
